"""secong Migration

Revision ID: 72ec66523a27
Revises: 5bd58fc892b8
Create Date: 2022-05-18 08:52:09.312463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ec66523a27'
down_revision = '5bd58fc892b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('posts', sa.Column('author_name', sa.String(length=255), nullable=False))
    op.drop_column('posts', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('posts', 'author_name')
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
